// <auto-generated />
using System;
using EFCore_FluentAPI_Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore_FluentAPI_Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200219192931_temp")]
    partial class temp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore_FluentAPI_Entity.Caderno", b =>
                {
                    b.Property<int>("CadernoId")
                        .HasColumnType("int");

                    b.Property<string>("AutorCaderno")
                        .IsConcurrencyToken()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("DataExpurgo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("TituloOutro")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("UltimoAcesso")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("CadernoId");

                    b.ToTable("Cadernos");
                });
#pragma warning restore 612, 618
        }
    }
}
