// <auto-generated />
using EFCore_Relacionamentos1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore_Relacionamentos1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200219234243_temp")]
    partial class temp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore_Relacionamentos1.Curso", b =>
                {
                    b.Property<int>("CodCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodCurso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("EFCore_Relacionamentos1.Estudante", b =>
                {
                    b.Property<int>("CodEstudante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodEstudante");

                    b.ToTable("Estudantes");
                });

            modelBuilder.Entity("EFCore_Relacionamentos1.EstudanteCurso", b =>
                {
                    b.Property<int>("CodCurso")
                        .HasColumnType("int");

                    b.Property<int>("CodEstudante")
                        .HasColumnType("int");

                    b.HasKey("CodCurso", "CodEstudante");

                    b.HasIndex("CodEstudante");

                    b.ToTable("EstudanteCursos");
                });

            modelBuilder.Entity("EFCore_Relacionamentos1.EstudanteCurso", b =>
                {
                    b.HasOne("EFCore_Relacionamentos1.Curso", "Curso")
                        .WithMany("EstudanteCursos")
                        .HasForeignKey("CodCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_Relacionamentos1.Estudante", "Estudante")
                        .WithMany("EstudanteCursos")
                        .HasForeignKey("CodEstudante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
